### ISSUE TITLE
Transactions visible only for configured IPC node

### ISSUE THREAD

**Issue by ice09** [gobitfly/etherchain-light#11]
I have different nodes (node0 and node1, both mining/validating), if in the etherchain-light config I choose the IPC path for node0, if the validating account is on this node, all transactions of this account are shown, if I change to node1, only those transactions of the validating account in that node are shown.

As a result, the balance of all accounts is correct, but the transaction list is filtered according to the mining accounts of the node with the configured IPC path, even if I don't want to.

Might be a conceptual limitation, then please comment and close issue.

**Comment by gobitfly** [comment]
Could you please provide a more detailed description of your use case? From your description it looks like your nodes are either not in sync or you run parity without the tracing flag?

**Comment by ice09** [comment]
Sure, I started all parity nodes with `--config nodeX.toml --tracing=on --fat-db=on --pruning=archive`.

All nodes show 0/2/25 peers in the console, so they know each other - don't know how to check if they are synched (btw: it's PoA from DemoPoA of parity).

this is the config (I just realized I left the names empty, but that shouldn't be a problem?)

```
  this.logFormat = "combined";
  this.ipcPath = process.env["HOME"] + "/dev/ethereum/2017/parity/node1/data/jsonrpc.ipc";
  this.provider = new web3.providers.IpcProvider(this.ipcPath, net);
  
  this.bootstrapUrl = "https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/yeti/bootstrap.min.css";
  
  this.names = {
  }
```

**Comment by ice09** [comment]
As a sidenote: I am not sure if `--tracing=on --fat-db=on --pruning=archive` has been activated from start, however it was activated for all the accounts in question.

**Comment by gobitfly** [comment]
From your description I assume that both of your nodes are not in sync, for whatever reason (e.g. you are using different config files for each node). As I did not receive any other similar issue reports I will close this issue for now.

**Comment by ice09** [comment]
For me it's ok to close it, but I am pretty sure that it can't be the synching, since for some time the peers display is 0/2/25 and is I understand it, the nodes wouldn't connect if the are not able to sync (due to different configs, etc.). Also, I used exactly the setup of DemoPoA, which means that the configs cannot really differ. 
But leave it closed, I will soon retry and use the flags --tracing... etc. from the beginning, probably it's working then, I will let you know.
