### ISSUE TITLE
parity data too big

### ISSUE THREAD

**Issue by bloonfield** [gobitfly/etherchain-light#14]
At around no.2900000 block，about 9MB is needed every block. So if I want a full-blockchain of eth, about 8TB disk sized is needed. I think there must be something wrong about parity.

**Comment by bloonfield** [comment]
I restarted the parity，the full size of the chain drops from 197GB to 111GB. I guess there's some cache stored on disk. So it's not 9MB ervery block. I'll see how much would it need when finished sync all data.

**Comment by gobitfly** [comment]
Using etherchain-light with the main Ethereum chain is not recommended. A full node sync with archive and fat-db enabled will consume ~300GB.
