### ISSUE TITLE
Explorer crashes when searched hash is not found

### ISSUE THREAD

**Issue by AyushyaChitransh** [gobitfly/etherchain-light#25]
The explorer crashes when a hash is returned as not found. There have been multiple instances to confirm this behavior. The error logs generated after the crash are as follows:

> /home/ubuntu/ayushya/blockchainExplorer2/routes/tx.js:73
>       web3.trace.transaction(result.hash, function(err, traces) {
>                                    ^
> 
> TypeError: Cannot read property 'hash' of null
>     at /home/ubuntu/ayushya/blockchainExplorer2/routes/tx.js:73:36
>     at nextTask (/home/ubuntu/ayushya/blockchainExplorer2/node_modules/async/dist/async.js:5297:14)
>     at next (/home/ubuntu/ayushya/blockchainExplorer2/node_modules/async/dist/async.js:5304:9)
>     at /home/ubuntu/ayushya/blockchainExplorer2/node_modules/async/dist/async.js:906:16
>     at Object.callback (/home/ubuntu/ayushya/blockchainExplorer2/routes/tx.js:70:9)
>     at /home/ubuntu/ayushya/blockchainExplorer2/node_modules/web3/lib/web3/method.js:142:25
>     at Object.<anonymous> (/home/ubuntu/ayushya/blockchainExplorer2/node_modules/web3/lib/web3/requestmanager.js:89:9)
>     at /home/ubuntu/ayushya/blockchainExplorer2/node_modules/web3/lib/web3/ipcprovider.js:66:44
>     at Array.forEach (native)
>     at Socket.<anonymous> (/home/ubuntu/ayushya/blockchainExplorer2/node_modules/web3/lib/web3/ipcprovider.js:50:47)

**Comment by AyushyaChitransh** [comment]
A workaround this issue is to use `forever` to run the server. As described in [comment](https://github.com/foreverjs/forever/issues/540#issuecomment-37762716), I am using `forever start -c "npm start" .` to run the server.

**Comment by ppratscher** [comment]
This issue has been fixed in #24 .
