### ISSUE TITLE
Last Transactions is empty

### ISSUE THREAD

**Issue by dostu** [gobitfly/etherchain-light#26]
I'm running a private Proof of Authority chain with Parity version Parity/v1.8.2-beta-1b6588c-20171025/x86_64-macos/rustc1.21.0.
I'm using config options from the README (--tracing=on --fat-db=on --pruning=archive).

I can see the list of all transactions, but when I open an account page, Last Transactions table is empty.

It is working correctly in the demo (https://light.etherchain.org/).

**Comment by ppratscher** [comment]
Do you get any errors from the etherchain-light console output when you browse the accounts page?

**Comment by dostu** [comment]
No, there are no errors shown. I'm wondering if the new Parity version is causing it. The demo (https://light.etherchain.org/) is running 1.6.7. Is anyone running 1.8.2 with etherchain-light?

**Comment by dostu** [comment]
This was fixed in the most recent version. Thanks.
