### ISSUE TITLE
Does etherchain-light work with geth?

### ISSUE THREAD

**Issue by avatar-lavventura** [gobitfly/etherchain-light#3]
I am using a private ethereum network. I boost my node by using `geth`. If I run `geth` on the background instead of `parity` would it work? Thank you.

**Comment by gobitfly** [comment]
Currently etherchain light uses certain RPC calls that are not available with geth, namely the trace and parity RPC modules. Certain pages which do not use those modules will work.

We might add basic support for geth in a coming version.

**Comment by zyairzy** [comment]
Hello! I'm using node by geth too. I found it's hard for me to replace function which uses in parity RPC.
@gobitfly  Would you please tell me whether the version to add basic support for geth is completed? Thank you
