### ISSUE TITLE
(Problem) After verifying a contract, it's 502

### ISSUE THREAD

**Issue by rstormsf** [gobitfly/etherchain-light#32]
https://light.etherchain.org/account/0x0190df91f46fe15717f7ba56ab71730e2e14802e
```
Error 502 Ray ID: 3c20e01e59ab41c3 • 2017-11-23 02:59:57 UTC
Bad gateway
```

**Comment by ppratscher** [comment]
Sometimes verification takes longer than the default timeout of our CDN provider which causes the 502 error. The deployed version is just for demo purposes, I suggest you setup a local instance of the explorer which will not have this kind of issue.
