### ISSUE TITLE
App crashes when browsing to /accounts if there are no accounts.

### ISSUE THREAD

**Issue by TrekDev** [gobitfly/etherchain-light#5]
``` Parity//v1.7.0-unstable-57770ce84-20170314/x86_64-linux-gnu/rustc1.15.1 ```
``` Etherchain-light commit b9ea0dcf927676e0d53e5c2c972b8cd2e85b18a0```

```
$ parity account list
[]
```

Browse to /accounts & the app crashes with:
```
/home/xxx/Development/TrekDev/etherchain-light/routes/accounts.js:20
      var lastAccount = accounts[accounts.length - 1];
                                         ^

TypeError: Cannot read property 'length' of null
```

PS. Big thanks for this app. Really useful for working through development issues on our private chains 👍

**Comment by gobitfly** [comment]
Thanks for your feedback. The issue has been resolved with the latest commit.
