### ISSUE TITLE
Geth Compatibility (Instead of Parity)

### ISSUE THREAD

**Issue by alexacostarua** [gobitfly/etherchain-light#51]
Is there anyway to make this block explorer work for geth nodes?

**Comment by lishuo5263** [comment]
same ask

**Comment by marcopiraccini** [comment]
+1

**Comment by hello2mao** [comment]
+1

**Comment by marcopiraccini** [comment]
Just curiosity: why this issue has been closed?

**Comment by alexacostarua** [comment]
I moved to a parity node. Lol I closed it because I moved on frankly.  Poa explorer will tell you the same thing, as will other high end explorers.


On Aug 7, 2018, at 2:38 PM, Marco <notifications@github.com<mailto:notifications@github.com>> wrote:


Just curiosity: why this issue has been closed?
