### ISSUE TITLE
Doesnt handle accounts with alot of txs very well

### ISSUE THREAD

**Issue by chrisfranko** [gobitfly/etherchain-light#9]
Anytime I try to load an address with a ton of tx's like say, poloniex, it just bogs the script down and essentially kills it. Might be better to scan the chain from genesis and store all the chain data in mongo or something.

Apparently this has already been considered in the README.md
So it would be cool if there was a flag we could set in the config to make it run light or with a db.

**Comment by gobitfly** [comment]
The main problem is that the explorer tries to retrieve all tx sent and received by a given address (see https://github.com/gobitfly/etherchain-light/blob/master/routes/account.js#L75 and https://github.com/gobitfly/etherchain-light/blob/master/routes/account.js#L80). It would be possible to limit that call to 100 blocks and implement pagination.

Generally I would like to avoid bringing in a database as that will increase the complexity of the application significantly.

**Comment by chrisfranko** [comment]
Yea of course, I think what ill end up doing is eventually adding a database to my fork of the software but in the meantime use current block number - 100 blocks. Thanks again for this great starting point.

**Comment by chrisfranko** [comment]
Actually it just hit me that adding pagination might be the easier solution. It could still loop through all of the tx's but in bites of 100 blocks

**Comment by gobitfly** [comment]
Will be resolved once https://github.com/paritytech/parity/issues/4858 has been implemented.
